// Importing createSlice from Redux Toolkit
// createSlice simplifies Redux logic by automatically generating actions and reducers
import { createSlice } from '@reduxjs/toolkit'

// Creating a slice of the Redux store for the "counter" feature
export const counterSlice = createSlice({
    // Unique name for this slice of state
    name: 'counter',

    // Initial state for the counter slice
    initialState: {
        value: 0  // Start the counter at 0
    },

    // Reducer functions that define how the state should change based on actions
    reducers: {
        // Action: increment
        // Increases the counter by 1
        increment: (state) => {
            state.value += 1  // Redux Toolkit uses Immer to allow direct state mutation
        },

        // Action: decrement
        // Decreases the counter by 1
        decrement: (state) => {
            state.value -= 1
        },

        // Action: reset
        // Resets the counter value to 0
        reset: (state) => {
            state.value = 0
        },

        // Action: incrementByAmount
        // Increases the counter by a specific amount provided in the action payload
        incrementByAmount: (state, action) => {
            // Convert payload to a number (in case it comes as a string)
            state.value += Number(action.payload)
        },
    },
})

// Exporting the action creators automatically generated by createSlice
// These are used in components to dispatch actions
export const { increment, decrement, incrementByAmount, reset } = counterSlice.actions

// Exporting the reducer function so it can be added to the Redux store
export default counterSlice.reducer
